package org.prateek.demoproject.demoproject.model;
import java.sql.*;
import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Business {
	String ATTRIBUTES_AMBIENCE_DIVEY;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_DIETARY_VEGAN;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAPPY_HOUR;	//VARCHAR2(26 BYTE)
	String HOURS_THURSDAY_OPEN;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_ORDER_AT_COUNTER;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_AFROAMERICAN;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_KIDS;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_BYOB;	//VARCHAR2(26 BYTE)
	String HOURS_FRIDAY_OPEN;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_LATENIGHT;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_OUTDOORSEATING;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_ALCOHOL;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_CLASSY;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_BYAPPOINTMENTONLY	;//VARCHAR2(26 BYTE)
	String ATTRIBUTES_PARKINGLOT;	//VARCHAR2(26 BYTE)
	String BUSINESS_ID;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCETOURISTY;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_CORKAGE;	//VARCHAR2(26 BYTE)
	String HOURS_TUESDAY_OPEN;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_BRUNCH;	//VARCHAR2(26 BYTE)
	String CATEGORIES;	//VARCHAR2(256 BYTE)
	String ATTRIBUTES_WAITERSERVICE;	//VARCHAR2(26 BYTE)
	String HOURS_MONDAY_OPEN;	//VARCHAR2(26 BYTE)
	String NAME ;  //	VARCHAR2(128 BYTE)
	String ATTRIBUTES_PARKINGSTREET; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_HIPSTER; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_BYOB_CORKAGE; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_STRAIGHTPERMS; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_MUSIC_LIVE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_DIETARY_DAIRYFREE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_MUSIC_BACKGROUND;	//VARCHAR2(26 BYTE)
	int ATTRIBUTES_PRICERANGE;	//NUMBER(4,0)
	String ATTRIBUTES_GOODFOR_BREAKFAST;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_PARKING_GARAGE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_MUSIC_KARAOKE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_DANCING;	//VARCHAR2(26 BYTE)
	int REVIEW_COUNT;	//NUMBER(5,0)
	String ATTRIBUTES_HAIR_ASIAN;	//VARCHAR2(26 BYTE)
	String STATE;	//VARCHAR2(2 BYTE)
	String ATTRIBUTES_ACCEPTSCREDITCARDS;	//VARCHAR2(26 BYTE)
	String HOURS_FRIDAY_CLOSE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_LUNCH;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_PARKING_VALET;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_TAKEOUT;	//VARCHAR2(26 BYTE)
	String FULL_ADDRESS;	//VARCHAR2(500 BYTE)
	String HOURS_THURSDAY_CLOSE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_COLORING;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_DESSERT;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_MUSIC_VIDEO;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_DIETARY_HALAL;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_TAKES_RESERVATIONS;	//VARCHAR2(26 BYTE)
	String HOURS_SATURDAY_OPEN;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_AGESALLOWED;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_TRENDY; 	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_DELIVERY;	//VARCHAR2(26 BYTE)
	String HOURS_WEDNESDAY_CLOSE;	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_WIFI ;	 //VARCHAR2(26 BYTE)
	String OPEN	; //VARCHAR2(26 BYTE)
	String CITY	; //VARCHAR2(21 BYTE)
	String ATTRIBUTES_WHEELCHAIR ;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_DIETARY_GLUTENFREE;	//VARCHAR2(26 BYTE)
	float STARS	;//NUMBER(5,1)
	String ATTRIBUTES_DIETARY_KOSHER;  	//VARCHAR2(26 BYTE)
	//TYPE	VARCHAR2(8 BYTE)
	String ATTRIBUTES_CATERS ;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_INTIMATE;   //	VARCHAR2(26 BYTE)
	float LATITUDE; //	NUMBER(12,10)
	String ATTRIBUTES_GOODFOR_DINNER;   //  	VARCHAR2(26 BYTE)
	String ATTRIBUTES_COATCHECK;  //	VARCHAR2(26 BYTE)
	float LONGITUDE ;  //	NUMBER(12,10)
	String HOURS_MONDAY_CLOSE	;//VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_EXTENSIONS;//	VARCHAR2(26 BYTE)
	String HOURS_TUESDAY_CLOSE; //	VARCHAR2(26 BYTE)
	String HOURS_SATURDAY_CLOSE ;   	//VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_KIDS;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_PARKING_VALIDATED; //	VARCHAR2(26 BYTE)
	String HOURS_SUNDAY_OPEN;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_ACCEPTSINSURANCE;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_MUSIC_DJ;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_DIETARY_SOYFREE;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_HASTV;   //	VARCHAR2(26 BYTE)
	String HOURS_SUNDAY_CLOSE;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_CASUAL ; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_PERMS;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_DOGSALLOWED ; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_DRIVETHRU; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_DIETARY_VEGETARIAN;  //	VARCHAR2(26 BYTE)
	String HOURS_WEDNESDAY_OPEN	; //VARCHAR2(26 BYTE)
	String ATTRIBUTES_NOISELEVEL;  //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_SMOKING; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_ATTIRE; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_HAIR_CURLY; //	VARCHAR2(26 BYTE)
	String ATTRIBUTES_GOODFOR_GROUPS;//	VARCHAR2(26 BYTE)
	String NEIGHBORHOODS;//	VARCHAR2(50 BYTE)
	String ATTRIBUTES_OPEN24HOURS	;//VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_ROMANTIC	;//VARCHAR2(26 BYTE)
	String ATTRIBUTES_MUSIC_JUKEBOX	;//VARCHAR2(26 BYTE)
	String ATTRIBUTES_AMBIENCE_UPSCALE;	//VARCHAR2(26 BYTE)

	public Business(){};
	public Business(String aTTRIBUTES_AMBIENCE_DIVEY, String aTTRIBUTES_DIETARY_VEGAN, String aTTRIBUTES_HAPPY_HOUR,
			String hOURS_THURSDAY_OPEN, String aTTRIBUTES_ORDER_AT_COUNTER, String aTTRIBUTES_HAIR_AFROAMERICAN,
			String aTTRIBUTES_HAIR_KIDS, String aTTRIBUTES_BYOB, String hOURS_FRIDAY_OPEN,
			String aTTRIBUTES_GOODFOR_LATENIGHT, String aTTRIBUTES_OUTDOORSEATING, String aTTRIBUTES_ALCOHOL,
			String aTTRIBUTES_AMBIENCE_CLASSY, String aTTRIBUTES_BYAPPOINTMENTONLY, String aTTRIBUTES_PARKINGLOT,
			String bUSINESS_ID, String aTTRIBUTES_AMBIENCETOURISTY, String aTTRIBUTES_CORKAGE,
			String hOURS_TUESDAY_OPEN, String aTTRIBUTES_GOODFOR_BRUNCH, String cATEGORIES,
			String aTTRIBUTES_WAITERSERVICE, String hOURS_MONDAY_OPEN, String nAME, String aTTRIBUTES_PARKINGSTREET,
			String aTTRIBUTES_AMBIENCE_HIPSTER, String aTTRIBUTES_BYOB_CORKAGE, String aTTRIBUTES_HAIR_STRAIGHTPERMS,
			String aTTRIBUTES_MUSIC_LIVE, String aTTRIBUTES_DIETARY_DAIRYFREE, String aTTRIBUTES_MUSIC_BACKGROUND,
			int aTTRIBUTES_PRICERANGE, String aTTRIBUTES_GOODFOR_BREAKFAST, String aTTRIBUTES_PARKING_GARAGE,
			String aTTRIBUTES_MUSIC_KARAOKE, String aTTRIBUTES_GOODFOR_DANCING, int rEVIEW_COUNT,
			String aTTRIBUTES_HAIR_ASIAN, String sTATE, String aTTRIBUTES_ACCEPTSCREDITCARDS, String hOURS_FRIDAY_CLOSE,
			String aTTRIBUTES_GOODFOR_LUNCH, String aTTRIBUTES_PARKING_VALET, String aTTRIBUTES_TAKEOUT,
			String fULL_ADDRESS, String hOURS_THURSDAY_CLOSE, String aTTRIBUTES_HAIR_COLORING,
			String aTTRIBUTES_GOODFOR_DESSERT, String aTTRIBUTES_MUSIC_VIDEO, String aTTRIBUTES_DIETARY_HALAL,
			String aTTRIBUTES_TAKES_RESERVATIONS, String hOURS_SATURDAY_OPEN, String aTTRIBUTES_AGESALLOWED,
			String aTTRIBUTES_AMBIENCE_TRENDY, String aTTRIBUTES_DELIVERY, String hOURS_WEDNESDAY_CLOSE,
			String aTTRIBUTES_WIFI, String oPEN, String cITY, String aTTRIBUTES_WHEELCHAIR,
			String aTTRIBUTES_DIETARY_GLUTENFREE, float sTARS, String aTTRIBUTES_DIETARY_KOSHER,
			String aTTRIBUTES_CATERS, String aTTRIBUTES_AMBIENCE_INTIMATE, float lATITUDE,
			String aTTRIBUTES_GOODFOR_DINNER, String aTTRIBUTES_COATCHECK, float lONGITUDE, String hOURS_MONDAY_CLOSE,
			String aTTRIBUTES_HAIR_EXTENSIONS, String hOURS_TUESDAY_CLOSE, String hOURS_SATURDAY_CLOSE,
			String aTTRIBUTES_GOODFOR_KIDS, String aTTRIBUTES_PARKING_VALIDATED, String hOURS_SUNDAY_OPEN,
			String aTTRIBUTES_ACCEPTSINSURANCE, String aTTRIBUTES_MUSIC_DJ, String aTTRIBUTES_DIETARY_SOYFREE,
			String aTTRIBUTES_HASTV, String hOURS_SUNDAY_CLOSE, String aTTRIBUTES_AMBIENCE_CASUAL,
			String aTTRIBUTES_HAIR_PERMS, String aTTRIBUTES_DOGSALLOWED, String aTTRIBUTES_DRIVETHRU,
			String aTTRIBUTES_DIETARY_VEGETARIAN, String hOURS_WEDNESDAY_OPEN, String aTTRIBUTES_NOISELEVEL,
			String aTTRIBUTES_SMOKING, String aTTRIBUTES_ATTIRE, String aTTRIBUTES_HAIR_CURLY,
			String aTTRIBUTES_GOODFOR_GROUPS, String nEIGHBORHOODS, String aTTRIBUTES_OPEN24HOURS,
			String aTTRIBUTES_AMBIENCE_ROMANTIC, String aTTRIBUTES_MUSIC_JUKEBOX, String aTTRIBUTES_AMBIENCE_UPSCALE) {
		super();
		ATTRIBUTES_AMBIENCE_DIVEY = aTTRIBUTES_AMBIENCE_DIVEY;
		ATTRIBUTES_DIETARY_VEGAN = aTTRIBUTES_DIETARY_VEGAN;
		ATTRIBUTES_HAPPY_HOUR = aTTRIBUTES_HAPPY_HOUR;
		HOURS_THURSDAY_OPEN = hOURS_THURSDAY_OPEN;
		ATTRIBUTES_ORDER_AT_COUNTER = aTTRIBUTES_ORDER_AT_COUNTER;
		ATTRIBUTES_HAIR_AFROAMERICAN = aTTRIBUTES_HAIR_AFROAMERICAN;
		ATTRIBUTES_HAIR_KIDS = aTTRIBUTES_HAIR_KIDS;
		ATTRIBUTES_BYOB = aTTRIBUTES_BYOB;
		HOURS_FRIDAY_OPEN = hOURS_FRIDAY_OPEN;
		ATTRIBUTES_GOODFOR_LATENIGHT = aTTRIBUTES_GOODFOR_LATENIGHT;
		ATTRIBUTES_OUTDOORSEATING = aTTRIBUTES_OUTDOORSEATING;
		ATTRIBUTES_ALCOHOL = aTTRIBUTES_ALCOHOL;
		ATTRIBUTES_AMBIENCE_CLASSY = aTTRIBUTES_AMBIENCE_CLASSY;
		ATTRIBUTES_BYAPPOINTMENTONLY = aTTRIBUTES_BYAPPOINTMENTONLY;
		ATTRIBUTES_PARKINGLOT = aTTRIBUTES_PARKINGLOT;
		BUSINESS_ID = bUSINESS_ID;
		ATTRIBUTES_AMBIENCETOURISTY = aTTRIBUTES_AMBIENCETOURISTY;
		ATTRIBUTES_CORKAGE = aTTRIBUTES_CORKAGE;
		HOURS_TUESDAY_OPEN = hOURS_TUESDAY_OPEN;
		ATTRIBUTES_GOODFOR_BRUNCH = aTTRIBUTES_GOODFOR_BRUNCH;
		CATEGORIES = cATEGORIES;
		ATTRIBUTES_WAITERSERVICE = aTTRIBUTES_WAITERSERVICE;
		HOURS_MONDAY_OPEN = hOURS_MONDAY_OPEN;
		NAME = nAME;
		ATTRIBUTES_PARKINGSTREET = aTTRIBUTES_PARKINGSTREET;
		ATTRIBUTES_AMBIENCE_HIPSTER = aTTRIBUTES_AMBIENCE_HIPSTER;
		ATTRIBUTES_BYOB_CORKAGE = aTTRIBUTES_BYOB_CORKAGE;
		ATTRIBUTES_HAIR_STRAIGHTPERMS = aTTRIBUTES_HAIR_STRAIGHTPERMS;
		ATTRIBUTES_MUSIC_LIVE = aTTRIBUTES_MUSIC_LIVE;
		ATTRIBUTES_DIETARY_DAIRYFREE = aTTRIBUTES_DIETARY_DAIRYFREE;
		ATTRIBUTES_MUSIC_BACKGROUND = aTTRIBUTES_MUSIC_BACKGROUND;
		ATTRIBUTES_PRICERANGE = aTTRIBUTES_PRICERANGE;
		ATTRIBUTES_GOODFOR_BREAKFAST = aTTRIBUTES_GOODFOR_BREAKFAST;
		ATTRIBUTES_PARKING_GARAGE = aTTRIBUTES_PARKING_GARAGE;
		ATTRIBUTES_MUSIC_KARAOKE = aTTRIBUTES_MUSIC_KARAOKE;
		ATTRIBUTES_GOODFOR_DANCING = aTTRIBUTES_GOODFOR_DANCING;
		REVIEW_COUNT = rEVIEW_COUNT;
		ATTRIBUTES_HAIR_ASIAN = aTTRIBUTES_HAIR_ASIAN;
		STATE = sTATE;
		ATTRIBUTES_ACCEPTSCREDITCARDS = aTTRIBUTES_ACCEPTSCREDITCARDS;
		HOURS_FRIDAY_CLOSE = hOURS_FRIDAY_CLOSE;
		ATTRIBUTES_GOODFOR_LUNCH = aTTRIBUTES_GOODFOR_LUNCH;
		ATTRIBUTES_PARKING_VALET = aTTRIBUTES_PARKING_VALET;
		ATTRIBUTES_TAKEOUT = aTTRIBUTES_TAKEOUT;
		FULL_ADDRESS = fULL_ADDRESS;
		HOURS_THURSDAY_CLOSE = hOURS_THURSDAY_CLOSE;
		ATTRIBUTES_HAIR_COLORING = aTTRIBUTES_HAIR_COLORING;
		ATTRIBUTES_GOODFOR_DESSERT = aTTRIBUTES_GOODFOR_DESSERT;
		ATTRIBUTES_MUSIC_VIDEO = aTTRIBUTES_MUSIC_VIDEO;
		ATTRIBUTES_DIETARY_HALAL = aTTRIBUTES_DIETARY_HALAL;
		ATTRIBUTES_TAKES_RESERVATIONS = aTTRIBUTES_TAKES_RESERVATIONS;
		HOURS_SATURDAY_OPEN = hOURS_SATURDAY_OPEN;
		ATTRIBUTES_AGESALLOWED = aTTRIBUTES_AGESALLOWED;
		ATTRIBUTES_AMBIENCE_TRENDY = aTTRIBUTES_AMBIENCE_TRENDY;
		ATTRIBUTES_DELIVERY = aTTRIBUTES_DELIVERY;
		HOURS_WEDNESDAY_CLOSE = hOURS_WEDNESDAY_CLOSE;
		ATTRIBUTES_WIFI = aTTRIBUTES_WIFI;
		OPEN = oPEN;
		CITY = cITY;
		ATTRIBUTES_WHEELCHAIR = aTTRIBUTES_WHEELCHAIR;
		ATTRIBUTES_DIETARY_GLUTENFREE = aTTRIBUTES_DIETARY_GLUTENFREE;
		STARS = sTARS;
		ATTRIBUTES_DIETARY_KOSHER = aTTRIBUTES_DIETARY_KOSHER;
		ATTRIBUTES_CATERS = aTTRIBUTES_CATERS;
		ATTRIBUTES_AMBIENCE_INTIMATE = aTTRIBUTES_AMBIENCE_INTIMATE;
		LATITUDE = lATITUDE;
		ATTRIBUTES_GOODFOR_DINNER = aTTRIBUTES_GOODFOR_DINNER;
		ATTRIBUTES_COATCHECK = aTTRIBUTES_COATCHECK;
		LONGITUDE = lONGITUDE;
		HOURS_MONDAY_CLOSE = hOURS_MONDAY_CLOSE;
		ATTRIBUTES_HAIR_EXTENSIONS = aTTRIBUTES_HAIR_EXTENSIONS;
		HOURS_TUESDAY_CLOSE = hOURS_TUESDAY_CLOSE;
		HOURS_SATURDAY_CLOSE = hOURS_SATURDAY_CLOSE;
		ATTRIBUTES_GOODFOR_KIDS = aTTRIBUTES_GOODFOR_KIDS;
		ATTRIBUTES_PARKING_VALIDATED = aTTRIBUTES_PARKING_VALIDATED;
		HOURS_SUNDAY_OPEN = hOURS_SUNDAY_OPEN;
		ATTRIBUTES_ACCEPTSINSURANCE = aTTRIBUTES_ACCEPTSINSURANCE;
		ATTRIBUTES_MUSIC_DJ = aTTRIBUTES_MUSIC_DJ;
		ATTRIBUTES_DIETARY_SOYFREE = aTTRIBUTES_DIETARY_SOYFREE;
		ATTRIBUTES_HASTV = aTTRIBUTES_HASTV;
		HOURS_SUNDAY_CLOSE = hOURS_SUNDAY_CLOSE;
		ATTRIBUTES_AMBIENCE_CASUAL = aTTRIBUTES_AMBIENCE_CASUAL;
		ATTRIBUTES_HAIR_PERMS = aTTRIBUTES_HAIR_PERMS;
		ATTRIBUTES_DOGSALLOWED = aTTRIBUTES_DOGSALLOWED;
		ATTRIBUTES_DRIVETHRU = aTTRIBUTES_DRIVETHRU;
		ATTRIBUTES_DIETARY_VEGETARIAN = aTTRIBUTES_DIETARY_VEGETARIAN;
		HOURS_WEDNESDAY_OPEN = hOURS_WEDNESDAY_OPEN;
		ATTRIBUTES_NOISELEVEL = aTTRIBUTES_NOISELEVEL;
		ATTRIBUTES_SMOKING = aTTRIBUTES_SMOKING;
		ATTRIBUTES_ATTIRE = aTTRIBUTES_ATTIRE;
		ATTRIBUTES_HAIR_CURLY = aTTRIBUTES_HAIR_CURLY;
		ATTRIBUTES_GOODFOR_GROUPS = aTTRIBUTES_GOODFOR_GROUPS;
		NEIGHBORHOODS = nEIGHBORHOODS;
		ATTRIBUTES_OPEN24HOURS = aTTRIBUTES_OPEN24HOURS;
		ATTRIBUTES_AMBIENCE_ROMANTIC = aTTRIBUTES_AMBIENCE_ROMANTIC;
		ATTRIBUTES_MUSIC_JUKEBOX = aTTRIBUTES_MUSIC_JUKEBOX;
		ATTRIBUTES_AMBIENCE_UPSCALE = aTTRIBUTES_AMBIENCE_UPSCALE;
	}
	public String getATTRIBUTES_AMBIENCE_DIVEY() {
		return ATTRIBUTES_AMBIENCE_DIVEY;
	}
	public void setATTRIBUTES_AMBIENCE_DIVEY(String aTTRIBUTES_AMBIENCE_DIVEY) {
		ATTRIBUTES_AMBIENCE_DIVEY = aTTRIBUTES_AMBIENCE_DIVEY;
	}
	public String getATTRIBUTES_DIETARY_VEGAN() {
		return ATTRIBUTES_DIETARY_VEGAN;
	}
	public void setATTRIBUTES_DIETARY_VEGAN(String aTTRIBUTES_DIETARY_VEGAN) {
		ATTRIBUTES_DIETARY_VEGAN = aTTRIBUTES_DIETARY_VEGAN;
	}
	public String getATTRIBUTES_HAPPY_HOUR() {
		return ATTRIBUTES_HAPPY_HOUR;
	}
	public void setATTRIBUTES_HAPPY_HOUR(String aTTRIBUTES_HAPPY_HOUR) {
		ATTRIBUTES_HAPPY_HOUR = aTTRIBUTES_HAPPY_HOUR;
	}
	public String getHOURS_THURSDAY_OPEN() {
		return HOURS_THURSDAY_OPEN;
	}
	public void setHOURS_THURSDAY_OPEN(String hOURS_THURSDAY_OPEN) {
		HOURS_THURSDAY_OPEN = hOURS_THURSDAY_OPEN;
	}
	public String getATTRIBUTES_ORDER_AT_COUNTER() {
		return ATTRIBUTES_ORDER_AT_COUNTER;
	}
	public void setATTRIBUTES_ORDER_AT_COUNTER(String aTTRIBUTES_ORDER_AT_COUNTER) {
		ATTRIBUTES_ORDER_AT_COUNTER = aTTRIBUTES_ORDER_AT_COUNTER;
	}
	public String getATTRIBUTES_HAIR_AFROAMERICAN() {
		return ATTRIBUTES_HAIR_AFROAMERICAN;
	}
	public void setATTRIBUTES_HAIR_AFROAMERICAN(String aTTRIBUTES_HAIR_AFROAMERICAN) {
		ATTRIBUTES_HAIR_AFROAMERICAN = aTTRIBUTES_HAIR_AFROAMERICAN;
	}
	public String getATTRIBUTES_HAIR_KIDS() {
		return ATTRIBUTES_HAIR_KIDS;
	}
	public void setATTRIBUTES_HAIR_KIDS(String aTTRIBUTES_HAIR_KIDS) {
		ATTRIBUTES_HAIR_KIDS = aTTRIBUTES_HAIR_KIDS;
	}
	public String getATTRIBUTES_BYOB() {
		return ATTRIBUTES_BYOB;
	}
	public void setATTRIBUTES_BYOB(String aTTRIBUTES_BYOB) {
		ATTRIBUTES_BYOB = aTTRIBUTES_BYOB;
	}
	public String getHOURS_FRIDAY_OPEN() {
		return HOURS_FRIDAY_OPEN;
	}
	public void setHOURS_FRIDAY_OPEN(String hOURS_FRIDAY_OPEN) {
		HOURS_FRIDAY_OPEN = hOURS_FRIDAY_OPEN;
	}
	public String getATTRIBUTES_GOODFOR_LATENIGHT() {
		return ATTRIBUTES_GOODFOR_LATENIGHT;
	}
	public void setATTRIBUTES_GOODFOR_LATENIGHT(String aTTRIBUTES_GOODFOR_LATENIGHT) {
		ATTRIBUTES_GOODFOR_LATENIGHT = aTTRIBUTES_GOODFOR_LATENIGHT;
	}
	public String getATTRIBUTES_OUTDOORSEATING() {
		return ATTRIBUTES_OUTDOORSEATING;
	}
	public void setATTRIBUTES_OUTDOORSEATING(String aTTRIBUTES_OUTDOORSEATING) {
		ATTRIBUTES_OUTDOORSEATING = aTTRIBUTES_OUTDOORSEATING;
	}
	public String getATTRIBUTES_ALCOHOL() {
		return ATTRIBUTES_ALCOHOL;
	}
	public void setATTRIBUTES_ALCOHOL(String aTTRIBUTES_ALCOHOL) {
		ATTRIBUTES_ALCOHOL = aTTRIBUTES_ALCOHOL;
	}
	public String getATTRIBUTES_AMBIENCE_CLASSY() {
		return ATTRIBUTES_AMBIENCE_CLASSY;
	}
	public void setATTRIBUTES_AMBIENCE_CLASSY(String aTTRIBUTES_AMBIENCE_CLASSY) {
		ATTRIBUTES_AMBIENCE_CLASSY = aTTRIBUTES_AMBIENCE_CLASSY;
	}
	public String getATTRIBUTES_BYAPPOINTMENTONLY() {
		return ATTRIBUTES_BYAPPOINTMENTONLY;
	}
	public void setATTRIBUTES_BYAPPOINTMENTONLY(String aTTRIBUTES_BYAPPOINTMENTONLY) {
		ATTRIBUTES_BYAPPOINTMENTONLY = aTTRIBUTES_BYAPPOINTMENTONLY;
	}
	public String getATTRIBUTES_PARKINGLOT() {
		return ATTRIBUTES_PARKINGLOT;
	}
	public void setATTRIBUTES_PARKINGLOT(String aTTRIBUTES_PARKINGLOT) {
		ATTRIBUTES_PARKINGLOT = aTTRIBUTES_PARKINGLOT;
	}
	public String getBUSINESS_ID() {
		return BUSINESS_ID;
	}
	public void setBUSINESS_ID(String bUSINESS_ID) {
		BUSINESS_ID = bUSINESS_ID;
	}
	public String getATTRIBUTES_AMBIENCETOURISTY() {
		return ATTRIBUTES_AMBIENCETOURISTY;
	}
	public void setATTRIBUTES_AMBIENCETOURISTY(String aTTRIBUTES_AMBIENCETOURISTY) {
		ATTRIBUTES_AMBIENCETOURISTY = aTTRIBUTES_AMBIENCETOURISTY;
	}
	public String getATTRIBUTES_CORKAGE() {
		return ATTRIBUTES_CORKAGE;
	}
	public void setATTRIBUTES_CORKAGE(String aTTRIBUTES_CORKAGE) {
		ATTRIBUTES_CORKAGE = aTTRIBUTES_CORKAGE;
	}
	public String getHOURS_TUESDAY_OPEN() {
		return HOURS_TUESDAY_OPEN;
	}
	public void setHOURS_TUESDAY_OPEN(String hOURS_TUESDAY_OPEN) {
		HOURS_TUESDAY_OPEN = hOURS_TUESDAY_OPEN;
	}
	public String getATTRIBUTES_GOODFOR_BRUNCH() {
		return ATTRIBUTES_GOODFOR_BRUNCH;
	}
	public void setATTRIBUTES_GOODFOR_BRUNCH(String aTTRIBUTES_GOODFOR_BRUNCH) {
		ATTRIBUTES_GOODFOR_BRUNCH = aTTRIBUTES_GOODFOR_BRUNCH;
	}
	public String getCATEGORIES() {
		return CATEGORIES;
	}
	public void setCATEGORIES(String cATEGORIES) {
		CATEGORIES = cATEGORIES;
	}
	public String getATTRIBUTES_WAITERSERVICE() {
		return ATTRIBUTES_WAITERSERVICE;
	}
	public void setATTRIBUTES_WAITERSERVICE(String aTTRIBUTES_WAITERSERVICE) {
		ATTRIBUTES_WAITERSERVICE = aTTRIBUTES_WAITERSERVICE;
	}
	public String getHOURS_MONDAY_OPEN() {
		return HOURS_MONDAY_OPEN;
	}
	public void setHOURS_MONDAY_OPEN(String hOURS_MONDAY_OPEN) {
		HOURS_MONDAY_OPEN = hOURS_MONDAY_OPEN;
	}
	public String getNAME() {
		return NAME;
	}
	public void setNAME(String nAME) {
		NAME = nAME;
	}
	public String getATTRIBUTES_PARKINGSTREET() {
		return ATTRIBUTES_PARKINGSTREET;
	}
	public void setATTRIBUTES_PARKINGSTREET(String aTTRIBUTES_PARKINGSTREET) {
		ATTRIBUTES_PARKINGSTREET = aTTRIBUTES_PARKINGSTREET;
	}
	public String getATTRIBUTES_AMBIENCE_HIPSTER() {
		return ATTRIBUTES_AMBIENCE_HIPSTER;
	}
	public void setATTRIBUTES_AMBIENCE_HIPSTER(String aTTRIBUTES_AMBIENCE_HIPSTER) {
		ATTRIBUTES_AMBIENCE_HIPSTER = aTTRIBUTES_AMBIENCE_HIPSTER;
	}
	public String getATTRIBUTES_BYOB_CORKAGE() {
		return ATTRIBUTES_BYOB_CORKAGE;
	}
	public void setATTRIBUTES_BYOB_CORKAGE(String aTTRIBUTES_BYOB_CORKAGE) {
		ATTRIBUTES_BYOB_CORKAGE = aTTRIBUTES_BYOB_CORKAGE;
	}
	public String getATTRIBUTES_HAIR_STRAIGHTPERMS() {
		return ATTRIBUTES_HAIR_STRAIGHTPERMS;
	}
	public void setATTRIBUTES_HAIR_STRAIGHTPERMS(String aTTRIBUTES_HAIR_STRAIGHTPERMS) {
		ATTRIBUTES_HAIR_STRAIGHTPERMS = aTTRIBUTES_HAIR_STRAIGHTPERMS;
	}
	public String getATTRIBUTES_MUSIC_LIVE() {
		return ATTRIBUTES_MUSIC_LIVE;
	}
	public void setATTRIBUTES_MUSIC_LIVE(String aTTRIBUTES_MUSIC_LIVE) {
		ATTRIBUTES_MUSIC_LIVE = aTTRIBUTES_MUSIC_LIVE;
	}
	public String getATTRIBUTES_DIETARY_DAIRYFREE() {
		return ATTRIBUTES_DIETARY_DAIRYFREE;
	}
	public void setATTRIBUTES_DIETARY_DAIRYFREE(String aTTRIBUTES_DIETARY_DAIRYFREE) {
		ATTRIBUTES_DIETARY_DAIRYFREE = aTTRIBUTES_DIETARY_DAIRYFREE;
	}
	public String getATTRIBUTES_MUSIC_BACKGROUND() {
		return ATTRIBUTES_MUSIC_BACKGROUND;
	}
	public void setATTRIBUTES_MUSIC_BACKGROUND(String aTTRIBUTES_MUSIC_BACKGROUND) {
		ATTRIBUTES_MUSIC_BACKGROUND = aTTRIBUTES_MUSIC_BACKGROUND;
	}
	public int getATTRIBUTES_PRICERANGE() {
		return ATTRIBUTES_PRICERANGE;
	}
	public void setATTRIBUTES_PRICERANGE(int aTTRIBUTES_PRICERANGE) {
		ATTRIBUTES_PRICERANGE = aTTRIBUTES_PRICERANGE;
	}
	public String getATTRIBUTES_GOODFOR_BREAKFAST() {
		return ATTRIBUTES_GOODFOR_BREAKFAST;
	}
	public void setATTRIBUTES_GOODFOR_BREAKFAST(String aTTRIBUTES_GOODFOR_BREAKFAST) {
		ATTRIBUTES_GOODFOR_BREAKFAST = aTTRIBUTES_GOODFOR_BREAKFAST;
	}
	public String getATTRIBUTES_PARKING_GARAGE() {
		return ATTRIBUTES_PARKING_GARAGE;
	}
	public void setATTRIBUTES_PARKING_GARAGE(String aTTRIBUTES_PARKING_GARAGE) {
		ATTRIBUTES_PARKING_GARAGE = aTTRIBUTES_PARKING_GARAGE;
	}
	public String getATTRIBUTES_MUSIC_KARAOKE() {
		return ATTRIBUTES_MUSIC_KARAOKE;
	}
	public void setATTRIBUTES_MUSIC_KARAOKE(String aTTRIBUTES_MUSIC_KARAOKE) {
		ATTRIBUTES_MUSIC_KARAOKE = aTTRIBUTES_MUSIC_KARAOKE;
	}
	public String getATTRIBUTES_GOODFOR_DANCING() {
		return ATTRIBUTES_GOODFOR_DANCING;
	}
	public void setATTRIBUTES_GOODFOR_DANCING(String aTTRIBUTES_GOODFOR_DANCING) {
		ATTRIBUTES_GOODFOR_DANCING = aTTRIBUTES_GOODFOR_DANCING;
	}
	public int getREVIEW_COUNT() {
		return REVIEW_COUNT;
	}
	public void setREVIEW_COUNT(int rEVIEW_COUNT) {
		REVIEW_COUNT = rEVIEW_COUNT;
	}
	public String getATTRIBUTES_HAIR_ASIAN() {
		return ATTRIBUTES_HAIR_ASIAN;
	}
	public void setATTRIBUTES_HAIR_ASIAN(String aTTRIBUTES_HAIR_ASIAN) {
		ATTRIBUTES_HAIR_ASIAN = aTTRIBUTES_HAIR_ASIAN;
	}
	public String getSTATE() {
		return STATE;
	}
	public void setSTATE(String sTATE) {
		STATE = sTATE;
	}
	public String getATTRIBUTES_ACCEPTSCREDITCARDS() {
		return ATTRIBUTES_ACCEPTSCREDITCARDS;
	}
	public void setATTRIBUTES_ACCEPTSCREDITCARDS(String aTTRIBUTES_ACCEPTSCREDITCARDS) {
		ATTRIBUTES_ACCEPTSCREDITCARDS = aTTRIBUTES_ACCEPTSCREDITCARDS;
	}
	public String getHOURS_FRIDAY_CLOSE() {
		return HOURS_FRIDAY_CLOSE;
	}
	public void setHOURS_FRIDAY_CLOSE(String hOURS_FRIDAY_CLOSE) {
		HOURS_FRIDAY_CLOSE = hOURS_FRIDAY_CLOSE;
	}
	public String getATTRIBUTES_GOODFOR_LUNCH() {
		return ATTRIBUTES_GOODFOR_LUNCH;
	}
	public void setATTRIBUTES_GOODFOR_LUNCH(String aTTRIBUTES_GOODFOR_LUNCH) {
		ATTRIBUTES_GOODFOR_LUNCH = aTTRIBUTES_GOODFOR_LUNCH;
	}
	public String getATTRIBUTES_PARKING_VALET() {
		return ATTRIBUTES_PARKING_VALET;
	}
	public void setATTRIBUTES_PARKING_VALET(String aTTRIBUTES_PARKING_VALET) {
		ATTRIBUTES_PARKING_VALET = aTTRIBUTES_PARKING_VALET;
	}
	public String getATTRIBUTES_TAKEOUT() {
		return ATTRIBUTES_TAKEOUT;
	}
	public void setATTRIBUTES_TAKEOUT(String aTTRIBUTES_TAKEOUT) {
		ATTRIBUTES_TAKEOUT = aTTRIBUTES_TAKEOUT;
	}
	public String getFULL_ADDRESS() {
		return FULL_ADDRESS;
	}
	public void setFULL_ADDRESS(String fULL_ADDRESS) {
		FULL_ADDRESS = fULL_ADDRESS;
	}
	public String getHOURS_THURSDAY_CLOSE() {
		return HOURS_THURSDAY_CLOSE;
	}
	public void setHOURS_THURSDAY_CLOSE(String hOURS_THURSDAY_CLOSE) {
		HOURS_THURSDAY_CLOSE = hOURS_THURSDAY_CLOSE;
	}
	public String getATTRIBUTES_HAIR_COLORING() {
		return ATTRIBUTES_HAIR_COLORING;
	}
	public void setATTRIBUTES_HAIR_COLORING(String aTTRIBUTES_HAIR_COLORING) {
		ATTRIBUTES_HAIR_COLORING = aTTRIBUTES_HAIR_COLORING;
	}
	public String getATTRIBUTES_GOODFOR_DESSERT() {
		return ATTRIBUTES_GOODFOR_DESSERT;
	}
	public void setATTRIBUTES_GOODFOR_DESSERT(String aTTRIBUTES_GOODFOR_DESSERT) {
		ATTRIBUTES_GOODFOR_DESSERT = aTTRIBUTES_GOODFOR_DESSERT;
	}
	public String getATTRIBUTES_MUSIC_VIDEO() {
		return ATTRIBUTES_MUSIC_VIDEO;
	}
	public void setATTRIBUTES_MUSIC_VIDEO(String aTTRIBUTES_MUSIC_VIDEO) {
		ATTRIBUTES_MUSIC_VIDEO = aTTRIBUTES_MUSIC_VIDEO;
	}
	public String getATTRIBUTES_DIETARY_HALAL() {
		return ATTRIBUTES_DIETARY_HALAL;
	}
	public void setATTRIBUTES_DIETARY_HALAL(String aTTRIBUTES_DIETARY_HALAL) {
		ATTRIBUTES_DIETARY_HALAL = aTTRIBUTES_DIETARY_HALAL;
	}
	public String getATTRIBUTES_TAKES_RESERVATIONS() {
		return ATTRIBUTES_TAKES_RESERVATIONS;
	}
	public void setATTRIBUTES_TAKES_RESERVATIONS(String aTTRIBUTES_TAKES_RESERVATIONS) {
		ATTRIBUTES_TAKES_RESERVATIONS = aTTRIBUTES_TAKES_RESERVATIONS;
	}
	public String getHOURS_SATURDAY_OPEN() {
		return HOURS_SATURDAY_OPEN;
	}
	public void setHOURS_SATURDAY_OPEN(String hOURS_SATURDAY_OPEN) {
		HOURS_SATURDAY_OPEN = hOURS_SATURDAY_OPEN;
	}
	public String getATTRIBUTES_AGESALLOWED() {
		return ATTRIBUTES_AGESALLOWED;
	}
	public void setATTRIBUTES_AGESALLOWED(String aTTRIBUTES_AGESALLOWED) {
		ATTRIBUTES_AGESALLOWED = aTTRIBUTES_AGESALLOWED;
	}
	public String getATTRIBUTES_AMBIENCE_TRENDY() {
		return ATTRIBUTES_AMBIENCE_TRENDY;
	}
	public void setATTRIBUTES_AMBIENCE_TRENDY(String aTTRIBUTES_AMBIENCE_TRENDY) {
		ATTRIBUTES_AMBIENCE_TRENDY = aTTRIBUTES_AMBIENCE_TRENDY;
	}
	public String getATTRIBUTES_DELIVERY() {
		return ATTRIBUTES_DELIVERY;
	}
	public void setATTRIBUTES_DELIVERY(String aTTRIBUTES_DELIVERY) {
		ATTRIBUTES_DELIVERY = aTTRIBUTES_DELIVERY;
	}
	public String getHOURS_WEDNESDAY_CLOSE() {
		return HOURS_WEDNESDAY_CLOSE;
	}
	public void setHOURS_WEDNESDAY_CLOSE(String hOURS_WEDNESDAY_CLOSE) {
		HOURS_WEDNESDAY_CLOSE = hOURS_WEDNESDAY_CLOSE;
	}
	public String getATTRIBUTES_WIFI() {
		return ATTRIBUTES_WIFI;
	}
	public void setATTRIBUTES_WIFI(String aTTRIBUTES_WIFI) {
		ATTRIBUTES_WIFI = aTTRIBUTES_WIFI;
	}
	public String getOPEN() {
		return OPEN;
	}
	public void setOPEN(String oPEN) {
		OPEN = oPEN;
	}
	public String getCITY() {
		return CITY;
	}
	public void setCITY(String cITY) {
		CITY = cITY;
	}
	public String getATTRIBUTES_WHEELCHAIR() {
		return ATTRIBUTES_WHEELCHAIR;
	}
	public void setATTRIBUTES_WHEELCHAIR(String aTTRIBUTES_WHEELCHAIR) {
		ATTRIBUTES_WHEELCHAIR = aTTRIBUTES_WHEELCHAIR;
	}
	public String getATTRIBUTES_DIETARY_GLUTENFREE() {
		return ATTRIBUTES_DIETARY_GLUTENFREE;
	}
	public void setATTRIBUTES_DIETARY_GLUTENFREE(String aTTRIBUTES_DIETARY_GLUTENFREE) {
		ATTRIBUTES_DIETARY_GLUTENFREE = aTTRIBUTES_DIETARY_GLUTENFREE;
	}
	public float getSTARS() {
		return STARS;
	}
	public void setSTARS(float sTARS) {
		STARS = sTARS;
	}
	public String getATTRIBUTES_DIETARY_KOSHER() {
		return ATTRIBUTES_DIETARY_KOSHER;
	}
	public void setATTRIBUTES_DIETARY_KOSHER(String aTTRIBUTES_DIETARY_KOSHER) {
		ATTRIBUTES_DIETARY_KOSHER = aTTRIBUTES_DIETARY_KOSHER;
	}
	public String getATTRIBUTES_CATERS() {
		return ATTRIBUTES_CATERS;
	}
	public void setATTRIBUTES_CATERS(String aTTRIBUTES_CATERS) {
		ATTRIBUTES_CATERS = aTTRIBUTES_CATERS;
	}
	public String getATTRIBUTES_AMBIENCE_INTIMATE() {
		return ATTRIBUTES_AMBIENCE_INTIMATE;
	}
	public void setATTRIBUTES_AMBIENCE_INTIMATE(String aTTRIBUTES_AMBIENCE_INTIMATE) {
		ATTRIBUTES_AMBIENCE_INTIMATE = aTTRIBUTES_AMBIENCE_INTIMATE;
	}
	public float getLATITUDE() {
		return LATITUDE;
	}
	public void setLATITUDE(float lATITUDE) {
		LATITUDE = lATITUDE;
	}
	public String getATTRIBUTES_GOODFOR_DINNER() {
		return ATTRIBUTES_GOODFOR_DINNER;
	}
	public void setATTRIBUTES_GOODFOR_DINNER(String aTTRIBUTES_GOODFOR_DINNER) {
		ATTRIBUTES_GOODFOR_DINNER = aTTRIBUTES_GOODFOR_DINNER;
	}
	public String getATTRIBUTES_COATCHECK() {
		return ATTRIBUTES_COATCHECK;
	}
	public void setATTRIBUTES_COATCHECK(String aTTRIBUTES_COATCHECK) {
		ATTRIBUTES_COATCHECK = aTTRIBUTES_COATCHECK;
	}
	public float getLONGITUDE() {
		return LONGITUDE;
	}
	public void setLONGITUDE(float lONGITUDE) {
		LONGITUDE = lONGITUDE;
	}
	public String getHOURS_MONDAY_CLOSE() {
		return HOURS_MONDAY_CLOSE;
	}
	public void setHOURS_MONDAY_CLOSE(String hOURS_MONDAY_CLOSE) {
		HOURS_MONDAY_CLOSE = hOURS_MONDAY_CLOSE;
	}
	public String getATTRIBUTES_HAIR_EXTENSIONS() {
		return ATTRIBUTES_HAIR_EXTENSIONS;
	}
	public void setATTRIBUTES_HAIR_EXTENSIONS(String aTTRIBUTES_HAIR_EXTENSIONS) {
		ATTRIBUTES_HAIR_EXTENSIONS = aTTRIBUTES_HAIR_EXTENSIONS;
	}
	public String getHOURS_TUESDAY_CLOSE() {
		return HOURS_TUESDAY_CLOSE;
	}
	public void setHOURS_TUESDAY_CLOSE(String hOURS_TUESDAY_CLOSE) {
		HOURS_TUESDAY_CLOSE = hOURS_TUESDAY_CLOSE;
	}
	public String getHOURS_SATURDAY_CLOSE() {
		return HOURS_SATURDAY_CLOSE;
	}
	public void setHOURS_SATURDAY_CLOSE(String hOURS_SATURDAY_CLOSE) {
		HOURS_SATURDAY_CLOSE = hOURS_SATURDAY_CLOSE;
	}
	public String getATTRIBUTES_GOODFOR_KIDS() {
		return ATTRIBUTES_GOODFOR_KIDS;
	}
	public void setATTRIBUTES_GOODFOR_KIDS(String aTTRIBUTES_GOODFOR_KIDS) {
		ATTRIBUTES_GOODFOR_KIDS = aTTRIBUTES_GOODFOR_KIDS;
	}
	public String getATTRIBUTES_PARKING_VALIDATED() {
		return ATTRIBUTES_PARKING_VALIDATED;
	}
	public void setATTRIBUTES_PARKING_VALIDATED(String aTTRIBUTES_PARKING_VALIDATED) {
		ATTRIBUTES_PARKING_VALIDATED = aTTRIBUTES_PARKING_VALIDATED;
	}
	public String getHOURS_SUNDAY_OPEN() {
		return HOURS_SUNDAY_OPEN;
	}
	public void setHOURS_SUNDAY_OPEN(String hOURS_SUNDAY_OPEN) {
		HOURS_SUNDAY_OPEN = hOURS_SUNDAY_OPEN;
	}
	public String getATTRIBUTES_ACCEPTSINSURANCE() {
		return ATTRIBUTES_ACCEPTSINSURANCE;
	}
	public void setATTRIBUTES_ACCEPTSINSURANCE(String aTTRIBUTES_ACCEPTSINSURANCE) {
		ATTRIBUTES_ACCEPTSINSURANCE = aTTRIBUTES_ACCEPTSINSURANCE;
	}
	public String getATTRIBUTES_MUSIC_DJ() {
		return ATTRIBUTES_MUSIC_DJ;
	}
	public void setATTRIBUTES_MUSIC_DJ(String aTTRIBUTES_MUSIC_DJ) {
		ATTRIBUTES_MUSIC_DJ = aTTRIBUTES_MUSIC_DJ;
	}
	public String getATTRIBUTES_DIETARY_SOYFREE() {
		return ATTRIBUTES_DIETARY_SOYFREE;
	}
	public void setATTRIBUTES_DIETARY_SOYFREE(String aTTRIBUTES_DIETARY_SOYFREE) {
		ATTRIBUTES_DIETARY_SOYFREE = aTTRIBUTES_DIETARY_SOYFREE;
	}
	public String getATTRIBUTES_HASTV() {
		return ATTRIBUTES_HASTV;
	}
	public void setATTRIBUTES_HASTV(String aTTRIBUTES_HASTV) {
		ATTRIBUTES_HASTV = aTTRIBUTES_HASTV;
	}
	public String getHOURS_SUNDAY_CLOSE() {
		return HOURS_SUNDAY_CLOSE;
	}
	public void setHOURS_SUNDAY_CLOSE(String hOURS_SUNDAY_CLOSE) {
		HOURS_SUNDAY_CLOSE = hOURS_SUNDAY_CLOSE;
	}
	public String getATTRIBUTES_AMBIENCE_CASUAL() {
		return ATTRIBUTES_AMBIENCE_CASUAL;
	}
	public void setATTRIBUTES_AMBIENCE_CASUAL(String aTTRIBUTES_AMBIENCE_CASUAL) {
		ATTRIBUTES_AMBIENCE_CASUAL = aTTRIBUTES_AMBIENCE_CASUAL;
	}
	public String getATTRIBUTES_HAIR_PERMS() {
		return ATTRIBUTES_HAIR_PERMS;
	}
	public void setATTRIBUTES_HAIR_PERMS(String aTTRIBUTES_HAIR_PERMS) {
		ATTRIBUTES_HAIR_PERMS = aTTRIBUTES_HAIR_PERMS;
	}
	public String getATTRIBUTES_DOGSALLOWED() {
		return ATTRIBUTES_DOGSALLOWED;
	}
	public void setATTRIBUTES_DOGSALLOWED(String aTTRIBUTES_DOGSALLOWED) {
		ATTRIBUTES_DOGSALLOWED = aTTRIBUTES_DOGSALLOWED;
	}
	public String getATTRIBUTES_DRIVETHRU() {
		return ATTRIBUTES_DRIVETHRU;
	}
	public void setATTRIBUTES_DRIVETHRU(String aTTRIBUTES_DRIVETHRU) {
		ATTRIBUTES_DRIVETHRU = aTTRIBUTES_DRIVETHRU;
	}
	public String getATTRIBUTES_DIETARY_VEGETARIAN() {
		return ATTRIBUTES_DIETARY_VEGETARIAN;
	}
	public void setATTRIBUTES_DIETARY_VEGETARIAN(String aTTRIBUTES_DIETARY_VEGETARIAN) {
		ATTRIBUTES_DIETARY_VEGETARIAN = aTTRIBUTES_DIETARY_VEGETARIAN;
	}
	public String getHOURS_WEDNESDAY_OPEN() {
		return HOURS_WEDNESDAY_OPEN;
	}
	public void setHOURS_WEDNESDAY_OPEN(String hOURS_WEDNESDAY_OPEN) {
		HOURS_WEDNESDAY_OPEN = hOURS_WEDNESDAY_OPEN;
	}
	public String getATTRIBUTES_NOISELEVEL() {
		return ATTRIBUTES_NOISELEVEL;
	}
	public void setATTRIBUTES_NOISELEVEL(String aTTRIBUTES_NOISELEVEL) {
		ATTRIBUTES_NOISELEVEL = aTTRIBUTES_NOISELEVEL;
	}
	public String getATTRIBUTES_SMOKING() {
		return ATTRIBUTES_SMOKING;
	}
	public void setATTRIBUTES_SMOKING(String aTTRIBUTES_SMOKING) {
		ATTRIBUTES_SMOKING = aTTRIBUTES_SMOKING;
	}
	public String getATTRIBUTES_ATTIRE() {
		return ATTRIBUTES_ATTIRE;
	}
	public void setATTRIBUTES_ATTIRE(String aTTRIBUTES_ATTIRE) {
		ATTRIBUTES_ATTIRE = aTTRIBUTES_ATTIRE;
	}
	public String getATTRIBUTES_HAIR_CURLY() {
		return ATTRIBUTES_HAIR_CURLY;
	}
	public void setATTRIBUTES_HAIR_CURLY(String aTTRIBUTES_HAIR_CURLY) {
		ATTRIBUTES_HAIR_CURLY = aTTRIBUTES_HAIR_CURLY;
	}
	public String getATTRIBUTES_GOODFOR_GROUPS() {
		return ATTRIBUTES_GOODFOR_GROUPS;
	}
	public void setATTRIBUTES_GOODFOR_GROUPS(String aTTRIBUTES_GOODFOR_GROUPS) {
		ATTRIBUTES_GOODFOR_GROUPS = aTTRIBUTES_GOODFOR_GROUPS;
	}
	public String getNEIGHBORHOODS() {
		return NEIGHBORHOODS;
	}
	public void setNEIGHBORHOODS(String nEIGHBORHOODS) {
		NEIGHBORHOODS = nEIGHBORHOODS;
	}
	public String getATTRIBUTES_OPEN24HOURS() {
		return ATTRIBUTES_OPEN24HOURS;
	}
	public void setATTRIBUTES_OPEN24HOURS(String aTTRIBUTES_OPEN24HOURS) {
		ATTRIBUTES_OPEN24HOURS = aTTRIBUTES_OPEN24HOURS;
	}
	public String getATTRIBUTES_AMBIENCE_ROMANTIC() {
		return ATTRIBUTES_AMBIENCE_ROMANTIC;
	}
	public void setATTRIBUTES_AMBIENCE_ROMANTIC(String aTTRIBUTES_AMBIENCE_ROMANTIC) {
		ATTRIBUTES_AMBIENCE_ROMANTIC = aTTRIBUTES_AMBIENCE_ROMANTIC;
	}
	public String getATTRIBUTES_MUSIC_JUKEBOX() {
		return ATTRIBUTES_MUSIC_JUKEBOX;
	}
	public void setATTRIBUTES_MUSIC_JUKEBOX(String aTTRIBUTES_MUSIC_JUKEBOX) {
		ATTRIBUTES_MUSIC_JUKEBOX = aTTRIBUTES_MUSIC_JUKEBOX;
	}
	public String getATTRIBUTES_AMBIENCE_UPSCALE() {
		return ATTRIBUTES_AMBIENCE_UPSCALE;
	}
	public void setATTRIBUTES_AMBIENCE_UPSCALE(String aTTRIBUTES_AMBIENCE_UPSCALE) {
		ATTRIBUTES_AMBIENCE_UPSCALE = aTTRIBUTES_AMBIENCE_UPSCALE;
	}



}
